# Generated by Django 5.2.6 on 2025-10-08 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payments",
            name="payment_sign_name",
        ),
    ]
