# Generated by Django 5.2.6 on 2025-09-26 12:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0002_alter_course_description_alter_lesson_course_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                help_text="Укажите создателя курса",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Имя пользователя",
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                help_text="Укажите создателя урока",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Имя пользователя",
            ),
        ),
    ]
